sudo: required
services:
  - docker

before_install:
  - docker build -t vishal/docker-react -f Dockerfile.dev .

script:
  - docker run vishal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "<enter your bucket name>"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
